# Generated by Django 2.0.7 on 2019-05-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ControlHedgeApiinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('exchangename', models.CharField(db_column='exchangeName', max_length=16)),
                ('account', models.CharField(max_length=32)),
                ('tag', models.CharField(max_length=126)),
                ('apikey', models.CharField(db_column='apiKey', max_length=64)),
                ('secretkey', models.CharField(db_column='secretKey', max_length=64)),
                ('jcuid', models.CharField(db_column='jcUid', max_length=16)),
            ],
            options={
                'db_table': 'control_hedge_apiinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ControlHedgePerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'control_hedge_person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ControlHedgeSymbolconfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=16)),
                ('amount', models.CharField(max_length=16)),
                ('price', models.CharField(max_length=16)),
                ('askprice', models.FloatField(db_column='askPrice')),
                ('bidprice', models.FloatField(db_column='bidPrice')),
                ('bidamount', models.FloatField(db_column='bidAmount')),
                ('askamount', models.FloatField(db_column='askAmount')),
                ('minamount', models.FloatField(db_column='minAmount')),
                ('maxamount', models.FloatField(db_column='maxAmount')),
                ('status', models.IntegerField()),
                ('depthstep', models.IntegerField(db_column='depthStep')),
                ('dealmaxamount', models.FloatField(db_column='dealMaxAmount')),
                ('dealproportion', models.FloatField(db_column='dealProportion')),
                ('dealwarningamount', models.FloatField(db_column='dealWarningAmount')),
            ],
            options={
                'db_table': 'control_hedge_symbol_config',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jc_order_id', models.CharField(max_length=48)),
                ('symbol', models.CharField(max_length=36)),
                ('base_symbol', models.CharField(max_length=18)),
                ('quote_symbol', models.CharField(max_length=18)),
                ('price', models.DecimalField(decimal_places=18, max_digits=32)),
                ('volume', models.DecimalField(decimal_places=18, max_digits=32)),
                ('side', models.CharField(max_length=8)),
                ('jc_ctime', models.CharField(max_length=36)),
                ('jc_cdate', models.CharField(max_length=36)),
                ('ome_name', models.CharField(max_length=36)),
                ('ome_order_id', models.CharField(blank=True, max_length=48, null=True)),
                ('ome_price', models.DecimalField(blank=True, decimal_places=18, max_digits=32, null=True)),
                ('ome_deal_price', models.DecimalField(blank=True, decimal_places=18, max_digits=32, null=True)),
                ('ome_deal_volume', models.DecimalField(blank=True, decimal_places=18, max_digits=32, null=True)),
                ('ome_volume', models.DecimalField(blank=True, decimal_places=18, max_digits=32, null=True)),
                ('fee', models.DecimalField(blank=True, decimal_places=18, max_digits=32, null=True)),
                ('ome_ctime', models.CharField(max_length=36)),
                ('ome_mtime', models.CharField(max_length=36)),
                ('status', models.CharField(max_length=2)),
                ('ctime', models.CharField(max_length=36)),
                ('mtime', models.CharField(max_length=36)),
            ],
            options={
                'db_table': 'order_info',
                'managed': False,
            },
        ),
    ]
