# Generated by Django 2.0.7 on 2019-05-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_hedge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
                ('exchangeName', models.CharField(default='', max_length=16)),
                ('account', models.CharField(default='', max_length=32)),
                ('tag', models.CharField(default='', max_length=126)),
                ('apiKey', models.CharField(default='', max_length=64)),
                ('secretKey', models.CharField(default='', max_length=64)),
                ('jcUid', models.CharField(default='', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SymbolConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='', max_length=16)),
                ('amount', models.CharField(default='', max_length=16)),
                ('price', models.CharField(default='', max_length=16)),
                ('askPrice', models.FloatField(default=1)),
                ('bidPrice', models.FloatField(default=1)),
                ('bidAmount', models.FloatField(default=1)),
                ('askAmount', models.FloatField(default=1)),
                ('minAmount', models.FloatField(default=0)),
                ('maxAmount', models.FloatField(default=0)),
                ('dealMaxAmount', models.FloatField(default=0)),
                ('dealProportion', models.FloatField(default=0)),
                ('dealWarningAmount', models.FloatField(default=0)),
                ('status', models.IntegerField(default=1)),
                ('depthStep', models.IntegerField(default=30)),
            ],
        ),
    ]
